// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVkoX5YLtqXTs6uqxjwstii_VxdVCKj1g',
    appId: '1:379361435835:web:041805fcd3b77f65b0c99e',
    messagingSenderId: '379361435835',
    projectId: 'uber-desmond',
    authDomain: 'uber-desmond.firebaseapp.com',
    storageBucket: 'uber-desmond.firebasestorage.app',
    measurementId: 'G-QVVXSWDPZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBL72FhS-Vvorh_ZODakDtY5W_FFWyTcc8',
    appId: '1:379361435835:android:2bf9ddc7bca43451b0c99e',
    messagingSenderId: '379361435835',
    projectId: 'uber-desmond',
    storageBucket: 'uber-desmond.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Qu7bOlMkQB9Csu7c-J5RLvPS9hEpUBM',
    appId: '1:379361435835:ios:44b070d060cf5b77b0c99e',
    messagingSenderId: '379361435835',
    projectId: 'uber-desmond',
    storageBucket: 'uber-desmond.firebasestorage.app',
    iosBundleId: 'com.example.healthapp',
  );
}
