// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfGLOgqJIMkO1KwuMNNA4ss0NznTdhkwk',
    appId: '1:393702954365:web:747d6691385d12dcfee814',
    messagingSenderId: '393702954365',
    projectId: 'soulsynchealth',
    authDomain: 'soulsynchealth.firebaseapp.com',
    databaseURL: 'https://soulsynchealth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsynchealth.firebasestorage.app',
    measurementId: 'G-KPTKWVCLQX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0kShEQN-lX20FmLrYbNztHwzyeHZ0nGU',
    appId: '1:393702954365:android:7ca6daefb00a169ffee814',
    messagingSenderId: '393702954365',
    projectId: 'soulsynchealth',
    databaseURL: 'https://soulsynchealth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsynchealth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjml7ULFN7k2AwWrZuvDQ4Zj2AE4MGKhE',
    appId: '1:393702954365:ios:8795c046e337b1c8fee814',
    messagingSenderId: '393702954365',
    projectId: 'soulsynchealth',
    databaseURL: 'https://soulsynchealth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsynchealth.firebasestorage.app',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjml7ULFN7k2AwWrZuvDQ4Zj2AE4MGKhE',
    appId: '1:393702954365:ios:8795c046e337b1c8fee814',
    messagingSenderId: '393702954365',
    projectId: 'soulsynchealth',
    databaseURL: 'https://soulsynchealth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsynchealth.firebasestorage.app',
    iosBundleId: 'com.example.healthapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfGLOgqJIMkO1KwuMNNA4ss0NznTdhkwk',
    appId: '1:393702954365:web:e54525ff42d329cdfee814',
    messagingSenderId: '393702954365',
    projectId: 'soulsynchealth',
    authDomain: 'soulsynchealth.firebaseapp.com',
    databaseURL: 'https://soulsynchealth-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'soulsynchealth.firebasestorage.app',
    measurementId: 'G-KN37EPVDD4',
  );

}